export const u: number = 0
export const r: number = 90
export const d: number = 180
export const l: number = 270
export const ul: number = 315
export const ur: number = 45
export const dr: number = 135
export const dl: number = 225
export const tlCorner: number[] = [r, d]
export const trCorner: number[] = [l, d]
export const blCorner: number[] = [r, u]
export const brCorner: number[] = [l, u]
export const wu: number[] = [u, u]
export const wd: number[] = [d, d]
export const wl: number[] = [l, l]
export const wr: number[] = [r, r]
export const hLine: number[] = [r, l]
export const vLine: number[] = [u, d]
export const empty = null
export const upArrow: number[] = [dr, dl]
export const downArrow: number[] = [ur, ul]
export const leftArrow: number[] = [ur, dr]
export const rightArrow: number[] = [ul, dl]
